<a href="https://colab.research.google.com/github/intothenewworld0805/bigdata-2025-1th/blob/main/20250402.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import requests

In [25]:
h_url = 'http://openapi.seoul.go.kr:8088/5763414a6567656e3939577755474d/json/TvEmgcHospitalInfo/1/100/'

h_response = requests.get(h_url)

In [26]:
h_data = h_response.json()
h_data

{'TvEmgcHospitalInfo': {'list_total_count': 72,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'HPID': 'A1100011',
    'DUTYADDR': '서울특별시 영등포구 63로 10, 여의도성모병원 (여의도동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '휴게시간 13:00~14:00',
    'DUTYINF': '저희 치과는 임플란트 보철 사랑니수술 등 치아에 관련된 모든 치료가능합니다(교정과도 같이 있음)',
    'DUTYMAPIMG': '샛강역 3번 출구',
    'DUTYNAME': '가톨릭대학교 여의도성모병원',
    'DUTYTEL1': '02-1661-7575',
    'DUTYTEL3': '02-3779-1188',
    'DUTYTIME1C': '1700',
    'DUTYTIME2C': '1700',
    'DUTYTIME3C': '1700',
    'DUTYTIME4C': '1700',
    'DUTYTIME5C': '1700',
    'DUTYTIME6C': '1200',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1400',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '1000',
    'DUTYTIME8S': '0930',
    'POSTCDN1': '073',
    'POSTCDN2': '45',
    'WGS84LON': '126.93673129599131',
    'WGS84LAT': '37.51827233800711',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1121013',
    'DUTYADDR': '서울특별시 은평구 통일로 1021 (진관동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '휴게시간 13:00~14:00',
    'DUTYINF': '저희 치과는 임플란트 보철 사랑니수술 등 치아에 관련된 모든 치료가능합니다(교정과도 같이 있음)',
    'DUTYMAPIMG': '샛강역 3번 출구',
    'DUTYNAME': '가톨릭대학교은평성모병원',
    'DUTYTEL1': '02-1811-7755',
    'DUTYTEL3': '02-1811-7755',
    'DUTYTIME1C': '1700',
    'DUTYTIME2C': '1700',
    'DUTYTIME3C': '1700',
    'DUTYTIME4C': '1700',
    'DUTYTIME5C': '1700',
    'DUTYTIME6C': '1200',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1400',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '1000',
    'DUTYTIME8S': '0930',
    'POSTCDN1': '033',
    'POSTCDN2': '12',
    'WGS84LON': '126.91615048739686',
    'WGS84LAT': '37.633608409726854',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1100047',
    'DUTYADDR': '서울특별시 관악구 관악로 242 (봉천동)',
    'DUTYDIV': 'B',
    'DUTYDIVNAM': '병원',
    'DUTYEMCLS': 'G009',
    'DUTYEMCLSNAME': '응급실운영신고기관',
    'DUTYERYN': '1',
    'DUTYETC': '응급실진료 07:00-24:00\n08/15 광복절 휴무',
    'DUTYINF': '화요일 야간진료 예약시 21시까지',
    'DUTYMAPIMG': '서울대입구역 7번 출구 도보 5분',
    'DUTYNAME': '강남고려병원',
    'DUTYTEL1': '1661-8267',
    'DUTYTEL3': '02-874-7227',
    'DUTYTIME1C': '1800',
    'DUTYTIME2C': '1800',
    'DUTYTIME3C': '1800',
    'DUTYTIME4C': '1800',
    'DUTYTIME5C': '1800',
    'DUTYTIME6C': '1300',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1730',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '1000',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '087',
    'POSTCDN2': '35',
    'WGS84LON': '126.956781703053',
    'WGS84LAT': '37.4856188363947',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1123234',
    'DUTYADDR': '서울특별시 강남구 선릉로 404, 더드림병원 (대치동)',
    'DUTYDIV': 'B',
    'DUTYDIVNAM': '병원',
    'DUTYEMCLS': 'G009',
    'DUTYEMCLSNAME': '응급실운영신고기관',
    'DUTYERYN': '1',
    'DUTYETC': '응급실 00:00-24:00',
    'DUTYINF': '화요일 야간진료 예약시 21시까지',
    'DUTYMAPIMG': '한티역 1번출구 3분거리',
    'DUTYNAME': '강남더드림병원',
    'DUTYTEL1': '02-1661-1177',
    'DUTYTEL3': '070-4676-5002',
    'DUTYTIME1C': '1800',
    'DUTYTIME2C': '1800',
    'DUTYTIME3C': '1800',
    'DUTYTIME4C': '1800',
    'DUTYTIME5C': '1800',
    'DUTYTIME6C': '1300',
    'DUTYTIME7C': '1700',
    'DUTYTIME8C': '1730',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '1100',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '061',
    'POSTCDN2': '98',
    'WGS84LON': '127.050967336445',
    'WGS84LAT': '37.5009902618151',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1100141',
    'DUTYADDR': '서울특별시 강남구 남부순환로 2649, 베드로병원 (도곡동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G009',
    'DUTYEMCLSNAME': '응급실운영신고기관',
    'DUTYERYN': '1',
    'DUTYETC': '외래 진료 운영시간 이외에는 응급의학과 전문의 근무',
    'DUTYINF': '24시간 응급실 운영\r\n응급의학과 정형외과(사지골절) 신경외과(뇌척추 수술) 내과(소화기, 순환기) 비뇨기과(요로결석, 전립선비대증) 산부인과 심장내과(심혈관 질환, 흉통) 신장내과(투석) 신경중재의학과(뇌혈관질환, 혈관색전술) 일반외과(갑상선) 영상의학과(CT, MRI) 준중환자실 8병상운영',
    'DUTYMAPIMG': '양재역 4번 출구 도보 5분 거리',
    'DUTYNAME': '강남베드로병원',
    'DUTYTEL1': '1544-7522',
    'DUTYTEL3': '1544-7522',
    'DUTYTIME1C': '2359',
    'DUTYTIME2C': '2359',
    'DUTYTIME3C': '2359',
    'DUTYTIME4C': '2359',
    'DUTYTIME5C': '2359',
    'DUTYTIME6C': '2359',
    'DUTYTIME7C': '2359',
    'DUTYTIME8C': '2359',
    'DUTYTIME1S': '0000',
    'DUTYTIME2S': '0000',
    'DUTYTIME3S': '0000',
    'DUTYTIME4S': '0000',
    'DUTYTIME5S': '0000',
    'DUTYTIME6S': '0000',
    'DUTYTIME7S': '0000',
    'DUTYTIME8S': '0000',
    'POSTCDN1': '062',
    'POSTCDN2': '71',
    'WGS84LON': '127.0395873429168',
    'WGS84LAT': '37.485612179925724',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1100076',
    'DUTYADDR': '서울특별시 관악구 남부순환로 1449, 강남힐병원 (신림동)',
    'DUTYDIV': 'B',
    'DUTYDIVNAM': '병원',
    'DUTYEMCLS': 'G009',
    'DUTYEMCLSNAME': '응급실운영신고기관',
    'DUTYERYN': '1',
    'DUTYETC': '24시간 응급실 운영\n내과/검진센터 2, 4주 토요일 휴진',
    'DUTYINF': '관악구 봉천동 187병상 투석 가능한 요양병원입니다.',
    'DUTYMAPIMG': '2호선 신대방역/난곡사거리 인근',
    'DUTYNAME': '강남힐병원',
    'DUTYTEL1': '02-853-4600',
    'DUTYTEL3': '02-853-9100',
    'DUTYTIME1C': '1800',
    'DUTYTIME2C': '1800',
    'DUTYTIME3C': '1800',
    'DUTYTIME4C': '1800',
    'DUTYTIME5C': '1800',
    'DUTYTIME6C': '1300',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1600',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '087',
    'POSTCDN2': '67',
    'WGS84LON': '126.911648078471',
    'WGS84LAT': '37.4816513439454',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1100043',
    'DUTYADDR': '서울특별시 강동구 동남로 892 (상일동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G001',
    'DUTYEMCLSNAME': '권역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '점심시간 13:00~14:00',
    'DUTYINF': '관악구 봉천동 187병상 투석 가능한 요양병원입니다.',
    'DUTYMAPIMG': '고덕역 4번 출구',
    'DUTYNAME': '강동경희대학교의대병원',
    'DUTYTEL1': '02-440-7114',
    'DUTYTEL3': '02-440-7000',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1200',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1600',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '052',
    'POSTCDN2': '78',
    'WGS84LON': '127.157084787845',
    'WGS84LAT': '37.5520459324005',
    'WORK_DTTM': '2025-03-07 15:14:36.0'},
   {'HPID': 'A1100006',
    'DUTYADDR': '서울특별시 종로구 새문안로 29 (평동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '휴게시간 13:00~14:00',
    'DUTYINF': '일요일 및 공휴일 진료 개시, 강북구 소재, 수면다원검사, 어지럼증, 귀코목진료, 청각장애진단, 보청기, 양압기 대여, 이비인후과 6인의 의료진',
    'DUTYMAPIMG': '서대문역 4번 출구',
    'DUTYNAME': '강북삼성병원',
    'DUTYTEL1': '02-2001-2001',
    'DUTYTEL3': '02-2001-1000',
    'DUTYTIME1C': '1700',
    'DUTYTIME2C': '1700',
    'DUTYTIME3C': '1700',
    'DUTYTIME4C': '1700',
    'DUTYTIME5C': '1700',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '1300',
    'DUTYTIME8C': '1300',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '031',
    'POSTCDN2': '81',
    'WGS84LON': '126.96793805451702',
    'WGS84LAT': '37.568497631233825',
    'WORK_DTTM': '2025-03-07 15:14:37.0'},
   {'HPID': 'A1121842',
    'DUTYADDR': '서울특별시 강북구 도봉로 187, 지하1층, 2층~5층 (미아동)',
    'DUTYDIV': 'B',
    'DUTYDIVNAM': '병원',
    'DUTYEMCLS': 'G009',
    'DUTYEMCLSNAME': '응급실운영신고기관',
    'DUTYERYN': '1',
    'DUTYETC': '점심시간 오후1시~2시\n365일 24시간 응급실 운영',
    'DUTYINF': '24시간 진료 정형외과 수술가능(골절, 수지접합등)',
    'DUTYMAPIMG': '답십리 사거리와 전농동 사거리 사이',
    'DUTYNAME': '강북으뜸병원',
    'DUTYTEL1': '02-986-0334',
    'DUTYTEL3': '02-986-0334',
    'DUTYTIME1C': '2000',
    'DUTYTIME2C': '1800',
    'DUTYTIME3C': '1800',
    'DUTYTIME4C': '2000',
    'DUTYTIME5C': '1800',
    'DUTYTIME6C': '1300',
    'DUTYTIME7C': '1500',
    'DUTYTIME8C': '1500',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '0800',
    'DUTYTIME8S': '0800',
    'POSTCDN1': '011',
    'POSTCDN2': '70',
    'WGS84LON': '127.026184524499',
    'WGS84LAT': '37.6254205559935',
    'WORK_DTTM': '2025-03-07 15:14:37.0'},
   {'HPID': 'A1117285',
    'DUTYADDR': '서울특별시 강서구 가로공원로 187, 강서케이병원 (화곡동)',
    'DUTYDIV': 'B',
    'DUTYDIVNAM': '병원',
    'DUTYEMCLS': 'G009',
    'DUTYEMCLSNAME': '응급실운영신고기관',
    'DUTYERYN': '1',
    'DUTYETC': '응급의료기관 외의 의료기관(응급의료시설) \n응급실 운영 - 골절, 외상, 척추, 관절 질환 24시간 365일 응급 진료 및 수술',
    'DUTYINF': '강서케이병원은 응급의료기관 외의 의료기관(응급의료시설)으로 24시간 365일 응급실 운영. 야간, 공휴일에도 골절, 외상, 관절, 척추 질환의 응급 진료 및 수술이 가능합니다. \n골절, 외상, 관절, 척추 질환을 전문으로 하며  3.0T MRI, 1.5T MRI, CT, X-ray, 초음파 등 전문 진단 장비를 갖추고 있습니다.',
    'DUTYMAPIMG': '화곡역 6번 출구, 가로공원 사거리',
    'DUTYNAME': '강서케이병원',
    'DUTYTEL1': '02-1833-7530',
    'DUTYTEL3': '02-6905-8585',
    'DUTYTIME1C': '1800',
    'DUTYTIME2C': '1800',
    'DUTYTIME3C': '1800',
    'DUTYTIME4C': '1800',
    'DUTYTIME5C': '1800',
    'DUTYTIME6C': '1300',
    'DUTYTIME7C': '1300',
    'DUTYTIME8C': '1300',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '077',
    'POSTCDN2': '18',
    'WGS84LON': '126.836699017573',
    'WGS84LAT': '37.5373576230977',
    'WORK_DTTM': '2025-03-07 15:14:37.0'},
   {'HPID': 'A1100002',
    'DUTYADDR': '서울특별시 광진구 능동로 120-1 (화양동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '점심시간:13~14시',
    'DUTYINF': '건강제일의료소비자생활협동조합',
    'DUTYMAPIMG': '건대입구역 3,4번 출구',
    'DUTYNAME': '건국대학교병원',
    'DUTYTEL1': '1588-1533',
    'DUTYTEL3': '02-2030-5555',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '1400',
    'DUTYTIME8C': '1400',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '1000',
    'DUTYTIME8S': '1000',
    'POSTCDN1': '050',
    'POSTCDN2': '30',
    'WGS84LON': '127.0721229093036',
    'WGS84LAT': '37.54084479467721',
    'WORK_DTTM': '2025-03-07 15:14:37.0'},
   {'HPID': 'A1100039',
    'DUTYADDR': '서울특별시 송파구 송이로 123, 국립경찰병원 (가락동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G007',
    'DUTYEMCLSNAME': '지역응급의료기관',
    'DUTYERYN': '1',
    'DUTYETC': '응급의료센터 - 24시간 진료',
    'DUTYINF': '보건복지부 지정 추나요법 시범사업기관입니다. 침, 한약, 추나, 면역약침등의 한의학적 치료방법을 이용하여 환자의 질병상태들 진단하고 치료합니다.',
    'DUTYMAPIMG': '경찰병원역 1,2번 출구',
    'DUTYNAME': '경찰병원',
    'DUTYTEL1': '02-3400-1114',
    'DUTYTEL3': '02-3400-1300',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1600',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '0930',
    'DUTYTIME8S': '0930',
    'POSTCDN1': '057',
    'POSTCDN2': '15',
    'WGS84LON': '127.12348793503201',
    'WGS84LAT': '37.496413213560785',
    'WORK_DTTM': '2025-03-07 15:14:37.0'},
   {'HPID': 'A1100001',
    'DUTYADDR': '서울특별시 동대문구 경희대로 23 (회기동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '10/1 (화) 임시공휴일, 10/3 (목) 개천절 : 09:30-13:00',
    'DUTYINF': '서울대입구역 2번 출구 100 미터 이내입니다 . 지하2층에 주차장 있읍니다 .',
    'DUTYMAPIMG': '영등포역 4번출구 파리바게트 건물',
    'DUTYNAME': '경희대학교병원',
    'DUTYTEL1': '02-958-8114',
    'DUTYTEL3': '02-958-8114',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '1800',
    'DUTYTIME8C': '1500',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '1000',
    'POSTCDN1': '024',
    'POSTCDN2': '47',
    'WGS84LON': '127.05183223390303',
    'WGS84LAT': '37.5938765502235',
    'WORK_DTTM': '2025-03-07 15:14:37.0'},
   {'HPID': 'A1100014',
    'DUTYADDR': '서울특별시 구로구 구로동로 148, 고려대부속구로병원 (구로동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G001',
    'DUTYEMCLSNAME': '권역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '점심시간 13:00~14:00',
    'DUTYINF': '야간진료\n - 월~금: 20시까지, 토: 17시까지',
    'DUTYMAPIMG': '구로구청 인근',
    'DUTYNAME': '고려대학교의과대학부속구로병원',
    'DUTYTEL1': '02-2626-1114',
    'DUTYTEL3': '02-2626-1550',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1200',
    'DUTYTIME7C': '1600',
    'DUTYTIME8C': '1600',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '1030',
    'DUTYTIME8S': '1030',
    'POSTCDN1': '083',
    'POSTCDN2': '08',
    'WGS84LON': '126.8847449363546',
    'WGS84LAT': '37.49211114525054',
    'WORK_DTTM': '2025-03-07 15:14:39.0'},
   {'HPID': 'A1100026',
    'DUTYADDR': '서울특별시 구로구 경인로 427, 구로성심병원 (고척동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G007',
    'DUTYEMCLSNAME': '지역응급의료기관',
    'DUTYERYN': '1',
    'DUTYETC': '점심시간 13:00~14:00',
    'DUTYINF': '안녕하세요? 최고의 치료가 될 수 있도록 최선을 다하는 구대한의원입니다. 머리떨림, 틱장애, 파킨슨병, 디스크 등의 질환을 치료합니다.',
    'DUTYMAPIMG': '구일역 2번 출구 고척 스카이 돔구장 맞은편',
    'DUTYNAME': '구로성심병원',
    'DUTYTEL1': '02-2067-1500',
    'DUTYTEL3': '02-2067-1515',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '1800',
    'DUTYTIME8C': '1800',
    'DUTYTIME1S': '0900',
    'DUTYTIME2S': '0900',
    'DUTYTIME3S': '0900',
    'DUTYTIME4S': '0900',
    'DUTYTIME5S': '0900',
    'DUTYTIME6S': '0900',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '082',
    'POSTCDN2': '23',
    'WGS84LON': '126.86636039556485',
    'WGS84LAT': '37.49964578669388',
    'WORK_DTTM': '2025-03-07 15:14:40.0'},
   {'HPID': 'A1100052',
    'DUTYADDR': '서울특별시 중구 을지로 245, 국립중앙의료원 (을지로6가)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '접수시간 : 평일 08:30~17:00 / 토요일 08:30~12:00\r\n진료시간 : 평일 09:00~17:00',
    'DUTYINF': '외래 30분전 접수마감/토요일은 일부과만 진료하며, 진료과 사정상 토요진료가 어려울 수 있으니 안내전화로 문의 후 내원하시기 바랍니다. \n☎ 1588-1775(ARS 안내)',
    'DUTYMAPIMG': '동대문역사문화공원역 13번출구 도보5분',
    'DUTYNAME': '국립중앙의료원',
    'DUTYTEL1': '02-2260-7114',
    'DUTYTEL3': '02-2276-2114',
    'DUTYTIME1C': '1700',
    'DUTYTIME2C': '1700',
    'DUTYTIME3C': '1700',
    'DUTYTIME4C': '1700',
    'DUTYTIME5C': '1700',
    'DUTYTIME6C': '1200',
    'DUTYTIME7C': '1300',
    'DUTYTIME8C': '1500',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '0800',
    'DUTYTIME8S': '0930',
    'POSTCDN1': '045',
    'POSTCDN2': '64',
    'WGS84LON': '127.00579539705472',
    'WGS84LAT': '37.56733955813183',
    'WORK_DTTM': '2025-03-07 15:14:40.0'},
   {'HPID': 'A1100048',
    'DUTYADDR': '서울특별시 노원구 한글비석로 68, 을지병원 (하계동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G006',
    'DUTYEMCLSNAME': '지역응급의료센터',
    'DUTYERYN': '1',
    'DUTYETC': '평일 13:00-14:00 휴게시간',
    'DUTYINF': '일반진료/미용성형/봉합/',
    'DUTYMAPIMG': '하계역 3번 출구',
    'DUTYNAME': '노원을지대학교병원',
    'DUTYTEL1': '02-970-8000',
    'DUTYTEL3': '02-970-8282',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '2200',
    'DUTYTIME8C': '1500',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '1000',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '018',
    'POSTCDN2': '30',
    'WGS84LON': '127.07000281991385',
    'WGS84LAT': '37.636442927386746',
    'WORK_DTTM': '2025-03-07 15:14:42.0'},
   {'HPID': 'A1100044',
    'DUTYADDR': '서울특별시 중랑구 사가정로49길 53 (면목동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G007',
    'DUTYEMCLSNAME': '지역응급의료기관',
    'DUTYERYN': '1',
    'DUTYETC': '',
    'DUTYINF': '일반진료/미용성형/봉합/',
    'DUTYMAPIMG': '사가정역 1번 출구/까치어린이공원 옆',
    'DUTYNAME': '녹색병원',
    'DUTYTEL1': '02-490-2000',
    'DUTYTEL3': '02-490-2113',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '2200',
    'DUTYTIME8C': '1500',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '1000',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '022',
    'POSTCDN2': '21',
    'WGS84LON': '127.08605546969357',
    'WGS84LAT': '37.58362083896108',
    'WORK_DTTM': '2025-03-07 15:14:42.0'},
   {'HPID': 'A1100037',
    'DUTYADDR': '서울특별시 영등포구 시흥대로 657 (대림동, 대림성모병원)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G007',
    'DUTYEMCLSNAME': '지역응급의료기관',
    'DUTYERYN': '1',
    'DUTYETC': '휴게시간 평일 13:00~14:00\n접수는 마감 10분 전까지',
    'DUTYINF': '정형외과 전문의가 진료하는 정형외과 의원입니다.',
    'DUTYMAPIMG': '구로디지털단지역 6번 출구 도보 10분',
    'DUTYNAME': '대림성모병원',
    'DUTYTEL1': '02-829-9000',
    'DUTYTEL3': '02-829-9129',
    'DUTYTIME1C': '1730',
    'DUTYTIME2C': '1730',
    'DUTYTIME3C': '1730',
    'DUTYTIME4C': '1730',
    'DUTYTIME5C': '1730',
    'DUTYTIME6C': '1230',
    'DUTYTIME7C': '1300',
    'DUTYTIME8C': '1500',
    'DUTYTIME1S': '0830',
    'DUTYTIME2S': '0830',
    'DUTYTIME3S': '0830',
    'DUTYTIME4S': '0830',
    'DUTYTIME5S': '0830',
    'DUTYTIME6S': '0830',
    'DUTYTIME7S': '0900',
    'DUTYTIME8S': '0900',
    'POSTCDN1': '074',
    'POSTCDN2': '42',
    'WGS84LON': '126.90716948025135',
    'WGS84LAT': '37.49068925436284',
    'WORK_DTTM': '2025-03-07 15:14:43.0'},
   {'HPID': 'A1100024',
    'DUTYADDR': '서울특별시 영등포구 도림로 156, 명지성모병원 (대림동)',
    'DUTYDIV': 'A',
    'DUTYDIVNAM': '종합병원',
    'DUTYEMCLS': 'G007',
    'DUTYEMCLSNAME': '지역응급의료기관',
    'DUTYERYN': '1',
    'DUTYETC': '점심시간 없이 진료',
    'DUTYINF': '보건복지부 지정 뇌혈관 전문병원 ( 종합병원 )',
    'DUTYMAPIMG': '대림역 11번 출구',
    'DUTYNAME': '명지성모병원',
    'DUTYTEL1': '02-1899-1475',
    'DUTYTEL3': '02-829-7800',
    'DUTYTIME1C': '1800',
    'DUTYTIME2C': '1730',

In [27]:
import pandas as pd

In [28]:
temp = []
for d in h_data['TvEmgcHospitalInfo']['row']:

  temp.append(d)

In [29]:
h_uni = pd.DataFrame(temp)
h_uni

,HPID,DUTYADDR,DUTYDIV,DUTYDIVNAM,DUTYEMCLS,DUTYEMCLSNAME,DUTYERYN,DUTYETC,DUTYINF,DUTYMAPIMG,...,DUTYTIME4S,DUTYTIME5S,DUTYTIME6S,DUTYTIME7S,DUTYTIME8S,POSTCDN1,POSTCDN2,WGS84LON,WGS84LAT,WORK_DTTM
0,A1100011,"서울특별시 영등포구 63로 10, 여의도성모병원 (여의도동)",A,종합병원,G006,지역응급의료센터,1,휴게시간 13:00~14:00,저희 치과는 임플란트 보철 사랑니수술 등 치아에 관련된 모든 치료가능합니다(교정과도...,샛강역 3번 출구,...,0900,0900,0900,1000,0930,073,45,126.93673129599131,37.51827233800711,2025-03-07 15:14:36.0
1,A1121013,서울특별시 은평구 통일로 1021 (진관동),A,종합병원,G006,지역응급의료센터,1,휴게시간 13:00~14:00,저희 치과는 임플란트 보철 사랑니수술 등 치아에 관련된 모든 치료가능합니다(교정과도...,샛강역 3번 출구,...,0830,0830,0830,1000,0930,033,12,126.91615048739686,37.633608409726854,2025-03-07 15:14:36.0
2,A1100047,서울특별시 관악구 관악로 242 (봉천동),B,병원,G009,응급실운영신고기관,1,응급실진료 07:00-24:00\n08/15 광복절 휴무,화요일 야간진료 예약시 21시까지,서울대입구역 7번 출구 도보 5분,...,0900,0900,0900,1000,0900,087,35,126.956781703053,37.4856188363947,2025-03-07 15:14:36.0
3,A1123234,"서울특별시 강남구 선릉로 404, 더드림병원 (대치동)",B,병원,G009,응급실운영신고기관,1,응급실 00:00-24:00,화요일 야간진료 예약시 21시까지,한티역 1번출구 3분거리,...,0900,0900,0900,1100,0900,061,98,127.050967336445,37.5009902618151,2025-03-07 15:14:36.0
4,A1100141,"서울특별시 강남구 남부순환로 2649, 베드로병원 (도곡동)",A,종합병원,G009,응급실운영신고기관,1,외래 진료 운영시간 이외에는 응급의학과 전문의 근무,24시간 응급실 운영\r\n응급의학과 정형외과(사지골절) 신경외과(뇌척추 수술) 내...,양재역 4번 출구 도보 5분 거리,...,0000,0000,0000,0000,0000,062,71,127.0395873429168,37.485612179925724,2025-03-07 15:14:36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,A1100038,"서울특별시 영등포구 버드나루로7길 12 (영등포동7가, 한강성심병원)",A,종합병원,G009,응급실운영신고기관,1,진료과에따라 상이함(연락 후 내원 바람),점심 12:30~13:30,서울특별시 영등포구 버드나루로7길 12 (영등포동 7가 94-200),...,0900,0900,0830,1000,1000,072,47,126.91033000120589,37.52346674579277,2025-03-07 15:15:04.0
68,A1100013,서울특별시 성동구 왕십리로 222-1 (사근동),A,종합병원,G001,권역응급의료센터,1,휴게시간 평일 13:00~14:00,관절염/류마티스 전문/,"한양대역 1번 출구\n왕십리역:6번,13번 출구->650M(도보10분)\n왕십리역:...",...,0830,0830,0830,0930,0900,047,63,127.04488284061982,37.559944533564746,2025-03-07 15:15:04.0
69,A1100051,서울특별시 광진구 자양로 85 (자양동),A,종합병원,G007,지역응급의료기관,1,휴게시간 평일 13:00~14:00,24시간 전문의 진료가 가능한 서울 동북부 지역 거점병원입니다.,2호선 구의역 4번출구 직진방향 5분 거리,...,0830,0830,0830,0900,0900,050,56,127.08360130258502,37.535315660180416,2025-03-07 15:15:05.0
70,A1100019,"서울특별시 양천구 목동로 225, 홍익병원본관 (신정동)",A,종합병원,G007,지역응급의료기관,1,토요일은 격주근무로 내원전 휴진여부 확인이 필요합니다.,후두내시경O/수액처치O,목동역 2번 출구,...,0900,0900,0900,0900,1030,079,37,126.8636640030062,37.52844147447355,2025-03-07 15:15:05.0
71,A1100049,서울특별시 금천구 시흥대로 244 (시흥동),A,종합병원,G007,지역응급의료기관,1,휴게시간 평일 13:00~14:00\n08/15 광복절 휴무,이비인후과는 토요일 휴진,금천구청역 1번 출구,...,0830,0830,0830,1000,1000,086,26,126.90056251863875,37.45567063464179,2025-03-07 15:15:06.0

In [30]:
pdData = pd.DataFrame(h_data)
pdData

                                                 TvEmgcHospitalInfo
list_total_count                                                 72
RESULT                {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}
row               [{'HPID': 'A1100011', 'DUTYADDR': '서울특별시 영등포구 ...

In [41]:
for n, row in h_uni.iterrows():
  print(n, 'DUTYDIVNAM	', row['WGS84LON'], row['WGS84LAT'])

0 DUTYDIVNAM	 126.93673129599131 37.51827233800711
1 DUTYDIVNAM	 126.91615048739686 37.633608409726854
2 DUTYDIVNAM	 126.956781703053 37.4856188363947
3 DUTYDIVNAM	 127.050967336445 37.5009902618151
4 DUTYDIVNAM	 127.0395873429168 37.485612179925724
5 DUTYDIVNAM	 126.911648078471 37.4816513439454
6 DUTYDIVNAM	 127.157084787845 37.5520459324005
7 DUTYDIVNAM	 126.96793805451702 37.568497631233825
8 DUTYDIVNAM	 127.026184524499 37.6254205559935
9 DUTYDIVNAM	 126.836699017573 37.5373576230977
10 DUTYDIVNAM	 127.0721229093036 37.54084479467721
11 DUTYDIVNAM	 127.12348793503201 37.496413213560785
12 DUTYDIVNAM	 127.05183223390303 37.5938765502235
13 DUTYDIVNAM	 126.8847449363546 37.49211114525054
14 DUTYDIVNAM	 126.86636039556485 37.49964578669388
15 DUTYDIVNAM	 127.00579539705472 37.56733955813183
16 DUTYDIVNAM	 127.07000281991385 37.636442927386746
17 DUTYDIVNAM	 127.08605546969357 37.58362083896108
18 DUTYDIVNAM	 126.90716948025135 37.49068925436284
19 DUTYDIVNAM	 126.89925446922592 37.4938507104387
20 DUTYDIVNAM	 126.83602535156236 37.55225379358291
21 DUTYDIVNAM	 126.85094950539181 37.556940892893586
22 DUTYDIVNAM	 126.956285774259 37.4796247835746
23 DUTYDIVNAM	 127.08668245340024 37.48851613490445
24 DUTYDIVNAM	 127.0653288266823 37.587992001305395
25 DUTYDIVNAM	 126.99896308412191 37.57966608924356
26 DUTYDIVNAM	 126.997196437908 37.5804523853297
27 DUTYDIVNAM	 127.04983805981972 37.58419129209865
28 DUTYDIVNAM	 126.96699861289684 37.56715536263689
29 DUTYDIVNAM	 127.03140257525507 37.57539886464885
30 DUTYDIVNAM	 126.92404876254014 37.4937184009319
31 DUTYDIVNAM	 126.8331299304024 37.51201935883779
32 DUTYDIVNAM	 127.0980910949257 37.61286931510163
33 DUTYDIVNAM	 127.028504374531 37.6402559204261
34 DUTYDIVNAM	 127.13526354631517 37.53598408220376
35 DUTYDIVNAM	 126.92236733617031 37.51205044957338
36 DUTYDIVNAM	 126.9577071892358 37.57534016994642
37 DUTYDIVNAM	 127.00441798640304 37.53384172231443
38 DUTYDIVNAM	 126.933734666413 37.5525892651719
39 DUTYDIVNAM	 126.90367981067837 37.518848328762154
40 DUTYDIVNAM	 127.04631254186797 37.492806984645476
41 DUTYDIVNAM	 126.94082769649863 37.56211711412639
42 DUTYDIVNAM	 126.7963653099318 37.56199597494205
43 DUTYDIVNAM	 126.917472218592 37.6146922208583
44 DUTYDIVNAM	 126.93658306608872 37.58110428173239
45 DUTYDIVNAM	 126.93253922577287 37.48427507045319
46 DUTYDIVNAM	 127.02267251878474 37.63547043209498
47 DUTYDIVNAM	 126.89561402986 37.526858089517
48 DUTYDIVNAM	 126.91955399169245 37.62079154435882
49 DUTYDIVNAM	 127.1090292210168 37.60067564592665
50 DUTYDIVNAM	 127.02902417950423 37.64611570419094
51 DUTYDIVNAM	 126.8862159683056 37.53654282637804
52 DUTYDIVNAM	 126.8362659275 37.557261149
53 DUTYDIVNAM	 127.06311619032102 37.6485812672986
54 DUTYDIVNAM	 126.98884533055192 37.5650731684839
55 DUTYDIVNAM	 127.05726710883552 37.49807126965969
56 DUTYDIVNAM	 127.028019796271 37.5651102845783
57 DUTYDIVNAM	 127.10823825113607 37.526563966361216
58 DUTYDIVNAM	 126.96079378447554 37.50707428493414
59 DUTYDIVNAM	 127.03466865188072 37.506800025850865
60 DUTYDIVNAM	 126.923855760856 37.604769594378
61 DUTYDIVNAM	 127.00472725970137 37.501800804785276
62 DUTYDIVNAM	 127.02647086385966 37.58715608002366
63 DUTYDIVNAM	 126.890913736375 37.5224047841717
64 DUTYDIVNAM	 127.14671886173552 37.528220900896635
65 DUTYDIVNAM	 127.08269315796588 37.628815981330355
66 DUTYDIVNAM	 126.9086725295 37.4932492859
67 DUTYDIVNAM	 126.91033000120589 37.52346674579277
68 DUTYDIVNAM	 127.04488284061982 37.559944533564746
69 DUTYDIVNAM	 127.08360130258502 37.535315660180416
70 DUTYDIVNAM	 126.8636640030062 37.52844147447355
71 DUTYDIVNAM	 126.90056251863875 37.45567063464179

In [32]:
import folium

In [36]:
anMap = folium.Map(location=[37.4965, 126.9573],
                   zoom_start=11,
                   zoom_control=False,
                   control_scale=True)
anMap

In [45]:
for n, row in h_uni.iterrows():
  mk = folium.Marker(location=[row['WGS84LON'], row['WGS84LAT']], popup=folium.Popup(row['DUTYNAME'], max_width=200))
  mk.add_to(anMap)
anMap

In [46]:
from folium.plugins import MarkerCluster
mc = MarkerCluster().add_to(anMap)

for n, row in h_uni.iterrows():
  folium.Marker(location=[ row['WGS84LAT'],row['WGS84LON']],
                popup = folium.Popup(row['DUTYNAME'], max_width=200)
                ).add_to(mc)
anMap